name: pre-queue-check
run-name: ${{ github.actor }} running pre-queue checks
on: 
  pull_request:
    types: [opened, reopened]
  
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - run: |
      echo LGTM