name: pre-queue-check

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: lgtm
    - run: echo lgtm
