name: pre-queue-check
run-name: ${{ github.actor }} running pre-queue checks
on: [pull_request]
  
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: lgtm
    - run: echo lgtm
