name: pre-queue-check

on: [push, pull_request]
  
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: lgtm
      run: |
        pwd
        ls -a
        bazelisk --version
